### ISSUE TITLE
node-proxy on Mac OS X

### ISSUE THREAD

**Issue by disenchant** [balupton/filepad#1]
I couln't manage to install the module **node-proxy** which is needed by **filepad**, even if I tried it manually:

```
disenchant-mba:docpad Disenchant$ sudo npm install node-proxy

> node-proxy@0.4.0 install /Users/Disenchant/lab/docpad/node_modules/node-proxy
> make

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
make: getcwd: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
BUILDING: C++ Component
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 16, in <module>
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
OSError: [Errno 13] Permission denied
/bin/sh: line 0: cd: ..: No such file or directory
make: *** [all] Error 1
npm ERR! error installing node-proxy@0.4.0 Error: node-proxy@0.4.0 install: `make`
npm ERR! error installing node-proxy@0.4.0 `sh "-c" "make"` failed with 2
npm ERR! error installing node-proxy@0.4.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing node-proxy@0.4.0     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing node-proxy@0.4.0     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! node-proxy@0.4.0 install: `make`
npm ERR! `sh "-c" "make"` failed with 2
npm ERR! 
npm ERR! Failed at the node-proxy@0.4.0 install script.
npm ERR! This is most likely a problem with the node-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-proxy
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "node-proxy"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Disenchant/lab/docpad/npm-debug.log
npm not ok
```

But there was no problem compiling it with the -g flag. Still **filepad** can't find the module afterwards.

```
disenchant-mba:docpad Disenchant$ sudo npm install -g node-proxy

> node-proxy@0.4.0 install /usr/local/lib/node_modules/node-proxy
> make

BUILDING: C++ Component
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.120s)
Waf: Entering directory `/usr/local/lib/node_modules/node-proxy/src/build'
[1/2] cxx: node-proxy.cc -> build/default/node-proxy_1.o
[2/2] cxx_link: build/default/node-proxy_1.o -> build/default/node-proxy.node
Waf: Leaving directory `/usr/local/lib/node_modules/node-proxy/src/build'
'build' finished successfully (0.805s)
node-proxy@0.4.0 /usr/local/lib/node_modules/node-proxy
```

**Comment by balupton** [comment]
https://github.com/balupton/filepad/issues/6
